language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2.0
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "psql -c 'create database latter_test;' -U postgres"
script: RAILS_ENV=test bundle exec rake db:migrate db:test:prepare spec
