GOOGLE_PRODUCTION_CLIENT_ID: '785970535978-est4ikrlfhdjgsh7idh9n26tss9tkut6.apps.googleusercontent.com'
GOOGLE_PRODUCTION_CLIENT_SECRET: 'PSj8-XLivAB4xSo84yqetKoQ'
GOOGLE_DEVELOPMENT_CLIENT_ID: '785970535978-erdjmirbrsuelin6i14rb15rjagrda1f.apps.googleusercontent.com'
GOOGLE_DEVELOPMENT_CLIENT_SECRET: 'zJtODqQj_eNVE2Nsb08NPE2X'
